import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { ApolloClient, InMemoryCache } from '@apollo/client'
import { GET_ALL_POSTS } from '@/graphql/query'
import Link from 'next/link'
import Router from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home({posts}) {
  console.log(posts);
  return (
    <>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <h1> welcome to the blog</h1>
     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
        Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
        when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
        It has survived not only five centuries, but also the leap into electronic typesetting, 
        remaining essentially unchanged. It was popularised in the 1960s with the release of 
        Letraset sheets containing Lorem Ipsum passages, and more recently
        with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
     </p>
     <br/>
     <h2>All posts</h2>
     <br/>
     {posts.map ((val, i) =>  {
      return(
        <Link key={i} href={val.attributes.Slug}legacyBehavior>
         <a>
            <div>
            <h3>{val.attributes.Title}</h3>
            <p>{val.attributes.Description}</p>
            </div>
            </a>
        </Link>
        
      )

     })}
    </>
  )
}

export async function getStaticProps (){
  const client = new ApolloClient ({
    uri:"http://127.0.0.1:1337/graphql",
    cache: new InMemoryCache()
 })

 const { data } = await client.query({
  query: GET_ALL_POSTS
 })

 return {
  props: {
    posts: data.blogPosts.data
  }
 }

}
